export const launchCategories = [
  {
    name: "公告",
    slug: "announcements",
    description: "站务公告、社区规则、版本更新、邀请和反馈收集。",
    color: "#7fb3ff",
    sortOrder: 10,
  },
  {
    name: "AI 工具",
    slug: "ai-tools",
    description: "Cursor、Codex、Claude Code、DeepSeek、Agent 和真实 AI 工作流。",
    color: "#66d08c",
    sortOrder: 20,
  },
  {
    name: "独立开发",
    slug: "indie-dev",
    description: "产品想法、MVP、技术选型、上线记录、冷启动、收入和失败复盘。",
    color: "#f3c969",
    sortOrder: 30,
  },
  {
    name: "SEO 与流量",
    slug: "seo-traffic",
    description: "Google SEO、内容站、社区推广、外链、广告变现和增长实验。",
    color: "#ff9f6e",
    sortOrder: 40,
  },
  {
    name: "效率工具",
    slug: "productivity-tools",
    description: "插件、脚本、自动化、个人知识库、开发环境和效率系统。",
    color: "#b794f4",
    sortOrder: 50,
  },
  {
    name: "项目展示",
    slug: "projects",
    description: "发布工具、插件、网站、小游戏、开源项目，并获得具体反馈。",
    color: "#ff7a98",
    sortOrder: 60,
  },
] as const;

export const launchTags = [
  { name: "Cursor", slug: "cursor", description: "Cursor 使用、插件开发和真实项目工作流。" },
  { name: "Codex", slug: "codex", description: "Codex 使用、开发协作和自动化。" },
  { name: "Claude Code", slug: "claude-code", description: "Claude Code 使用经验、对比和工程流。" },
  { name: "DeepSeek", slug: "deepseek", description: "DeepSeek API、模型能力和接入经验。" },
  { name: "AI Agent", slug: "ai-agent", description: "Agent 任务、自治流程、审核和协作边界。" },
  { name: "AI 工作流", slug: "ai-workflow", description: "从需求、编码、调试到发布的 AI 辅助流程。" },
  { name: "AI 写作", slug: "ai-writing", description: "AI 辅助写作、润色、摘要和去 AI 味。" },
  { name: "模型接入", slug: "model-integration", description: "大模型 API 配置、调用、容错和成本控制。" },
  { name: "独立开发", slug: "indie-dev", description: "独立开发过程、决策、复盘和长期经营。" },
  { name: "MVP", slug: "mvp", description: "最小可行产品、范围控制和首版取舍。" },
  { name: "冷启动", slug: "cold-start", description: "早期用户、内容、反馈和第一波流量获取。" },
  { name: "上线复盘", slug: "launch-retrospective", description: "产品、插件或网站上线后的数据和经验复盘。" },
  { name: "失败复盘", slug: "failure-review", description: "失败项目、错误判断和踩坑总结。" },
  { name: "用户反馈", slug: "user-feedback", description: "获取反馈、整理需求和验证问题。" },
  { name: "产品验证", slug: "product-validation", description: "需求验证、目标用户、付费意愿和市场判断。" },
  { name: "SEO", slug: "seo", description: "搜索引擎优化、索引、关键词和搜索流量。" },
  { name: "内容站", slug: "content-site", description: "内容站选题、结构、更新节奏和长尾内容。" },
  { name: "Google 搜索", slug: "google-search", description: "Google 收录、排名、Search Console 和流量观察。" },
  { name: "AdSense", slug: "adsense", description: "广告变现、接入条件、页面质量和收益观察。" },
  { name: "流量增长", slug: "traffic-growth", description: "SEO、社区、内容分发和增长实验。" },
  { name: "社区运营", slug: "community-ops", description: "小社区冷启动、规则、审核和内容节奏。" },
  { name: "自动化", slug: "automation", description: "脚本、定时任务、CI 和重复流程自动化。" },
  { name: "GitHub Actions", slug: "github-actions", description: "GitHub Actions 自动化、部署和开发流程。" },
  { name: "Docker", slug: "docker", description: "Docker 部署、镜像、构建和国内网络问题。" },
  { name: "VPS", slug: "vps", description: "云服务器部署、资源评估、运维和成本。" },
  { name: "PostgreSQL", slug: "postgresql", description: "PostgreSQL 数据库、全文搜索、迁移和运维。" },
  { name: "Cursor 插件", slug: "cursor-plugin", description: "Cursor / VS Code 插件设计、发布和推广。" },
  { name: "知识库", slug: "knowledge-base", description: "个人知识库、搜索、图谱和工作台。" },
  { name: "项目展示", slug: "project-showcase", description: "项目发布、Demo、进度记录和展示结构。" },
  { name: "求反馈", slug: "feedback", description: "请求具体反馈、测试和建议。" },
  { name: "开源", slug: "open-source", description: "开源项目、仓库运营、Issue 和社区协作。" },
  { name: "插件", slug: "plugin", description: "浏览器、编辑器、工具插件和扩展。" },
  { name: "小游戏", slug: "mini-game", description: "小游戏站、H5 游戏、内容站和广告实验。" },
  { name: "备案", slug: "icp", description: "域名、备案、服务器和上线前准备。" },
  { name: "Open VSX", slug: "open-vsx", description: "Open VSX 插件发布、README、截图和下载增长。" },
] as const;
