import type { CharacterConfig } from "../core/types";

export const characters: CharacterConfig[] = [
  {
    id: "engineer",
    name: "工程师",
    role: "多弹反弹",
    rarity: "common",
    color: "#61e6a8",
    marbles: ["basic", "split"],
    skillName: "折返板",
    skillDesc: "6 秒内弹珠反弹后增伤翻倍",
    skillCooldown: 18,
    passives: [
      { id: "engineer_structure", name: "结构熟手", unlockLevel: 3, desc: "物理/多弹标签弹珠伤害 +8%" },
      { id: "engineer_maintenance", name: "高频维护", unlockLevel: 6, desc: "发射频率 +8%" },
      { id: "engineer_replica", name: "弹道复写", unlockLevel: 10, desc: "普通发射有 10% 概率追加一颗小型弹珠" },
    ],
    routes: [
      {
        id: "engineer_overclock",
        name: "超频发射",
        focus: "射速",
        desc: "工程师弹珠发射频率 +4% / 级",
        max: 8,
        baseCost: 70,
        growth: 1.42,
      },
      {
        id: "engineer_rebound",
        name: "折返结构",
        focus: "反弹",
        desc: "基础/分裂弹珠伤害 +4%，每 2 级反弹 +1",
        max: 8,
        baseCost: 80,
        growth: 1.46,
      },
      {
        id: "engineer_field",
        name: "力场维护",
        focus: "技能",
        desc: "技能冷却 -3%，持续时间 +0.4 秒 / 级",
        max: 6,
        baseCost: 100,
        growth: 1.5,
      },
    ],
  },
  {
    id: "bomber",
    name: "爆破手",
    role: "范围燃烧",
    rarity: "rare",
    color: "#f6c95f",
    marbles: ["blast", "burn"],
    skillName: "高爆弹",
    skillDesc: "轰炸敌人最密集区域",
    skillCooldown: 20,
    passives: [
      { id: "bomber_charge", name: "装药专家", unlockLevel: 3, desc: "爆裂/燃烧弹珠伤害 +10%" },
      { id: "bomber_afterburn", name: "余焰燃剂", unlockLevel: 6, desc: "燃烧持续和伤害 +15%" },
      { id: "bomber_chain", name: "连锁爆破", unlockLevel: 10, desc: "爆炸半径 +12%" },
    ],
    routes: [
      {
        id: "bomber_blast",
        name: "爆心扩张",
        focus: "爆炸",
        desc: "爆裂伤害 +5%，爆炸半径 +3% / 级",
        max: 8,
        baseCost: 85,
        growth: 1.45,
      },
      {
        id: "bomber_burn",
        name: "热熔燃剂",
        focus: "燃烧",
        desc: "燃烧伤害 +6%，燃烧持续 +0.08 秒 / 级",
        max: 8,
        baseCost: 80,
        growth: 1.44,
      },
      {
        id: "bomber_supply",
        name: "弹药补给",
        focus: "循环",
        desc: "发射频率 +3%，技能冷却 -2.5% / 级",
        max: 6,
        baseCost: 105,
        growth: 1.52,
      },
    ],
  },
  {
    id: "magnetist",
    name: "磁能师",
    role: "连锁控制",
    rarity: "rare",
    color: "#54c7ff",
    marbles: ["lightning", "slow"],
    skillName: "磁场",
    skillDesc: "7 秒内弹珠轻微追踪敌人",
    skillCooldown: 22,
    passives: [
      { id: "magnetist_coil", name: "线圈增幅", unlockLevel: 3, desc: "闪电/减速弹珠伤害 +8%" },
      { id: "magnetist_conductor", name: "导流磁轨", unlockLevel: 6, desc: "闪电连锁 +1，减速持续 +0.25 秒" },
      { id: "magnetist_resonance", name: "磁场余波", unlockLevel: 10, desc: "磁场持续 +1.2 秒" },
    ],
    routes: [
      {
        id: "magnetist_chain",
        name: "电弧中继",
        focus: "连锁",
        desc: "闪电伤害 +4%，每 3 级连锁 +1",
        max: 8,
        baseCost: 80,
        growth: 1.45,
      },
      {
        id: "magnetist_control",
        name: "迟滞磁域",
        focus: "控制",
        desc: "控制弹珠伤害 +4%，减速强度 +2.5% / 级",
        max: 8,
        baseCost: 82,
        growth: 1.46,
      },
      {
        id: "magnetist_focus",
        name: "聚焦牵引",
        focus: "技能",
        desc: "技能冷却 -2.5%，磁场持续 +0.45 秒 / 级",
        max: 6,
        baseCost: 108,
        growth: 1.52,
      },
    ],
  },
  {
    id: "sentinel",
    name: "守卫者",
    role: "防线压制",
    rarity: "rare",
    color: "#ff8fb3",
    marbles: ["basic", "slow"],
    skillName: "防线回收",
    skillDesc: "修复基地并压制靠近底线的敌人",
    skillCooldown: 24,
    passives: [
      { id: "sentinel_wall", name: "坚壁阵列", unlockLevel: 3, desc: "基地生命上限 +1" },
      { id: "sentinel_fireline", name: "压制火线", unlockLevel: 6, desc: "基础/减速弹珠穿透 +1" },
      { id: "sentinel_repair", name: "应急回修", unlockLevel: 10, desc: "每 3 波结束额外修复 1 点基地生命" },
    ],
    routes: [
      {
        id: "sentinel_pierce",
        name: "穿甲弹道",
        focus: "穿透",
        desc: "基础/减速弹珠伤害 +4%，每 3 级穿透 +1",
        max: 8,
        baseCost: 82,
        growth: 1.45,
      },
      {
        id: "sentinel_barrier",
        name: "应急护壁",
        focus: "防御",
        desc: "技能冷却 -3%，每 3 级额外修复 1 点基地生命",
        max: 6,
        baseCost: 112,
        growth: 1.52,
      },
      {
        id: "sentinel_suppress",
        name: "压制阵列",
        focus: "减速",
        desc: "减速弹珠伤害 +4%，减速强度 +2% / 级",
        max: 8,
        baseCost: 86,
        growth: 1.46,
      },
    ],
  },
  {
    id: "prism",
    name: "棱镜师",
    role: "连锁折射",
    rarity: "epic",
    color: "#d58cff",
    marbles: ["lightning", "split"],
    skillName: "棱镜齐射",
    skillDesc: "短时间释放多颗折射弹珠",
    skillCooldown: 23,
    passives: [
      { id: "prism_calibration", name: "折射校准", unlockLevel: 3, desc: "闪电/分裂弹珠伤害 +8%" },
      { id: "prism_facets", name: "镜面分裂", unlockLevel: 6, desc: "分裂弹珠存在时间 +0.4 秒，小型分裂弹伤害 +12%" },
      { id: "prism_afterglow", name: "余光连锁", unlockLevel: 10, desc: "闪电连锁 +1" },
    ],
    routes: [
      {
        id: "prism_chain",
        name: "电弧折射",
        focus: "连锁",
        desc: "闪电伤害 +4%，每 3 级连锁 +1",
        max: 8,
        baseCost: 86,
        growth: 1.46,
      },
      {
        id: "prism_split",
        name: "多面分光",
        focus: "分裂",
        desc: "分裂弹珠伤害 +4%，存在时间 +0.15 秒 / 级",
        max: 8,
        baseCost: 84,
        growth: 1.45,
      },
      {
        id: "prism_burst",
        name: "折射矩阵",
        focus: "技能",
        desc: "技能冷却 -2.5%，每 2 级技能额外发射 1 颗弹珠",
        max: 6,
        baseCost: 112,
        growth: 1.52,
      },
    ],
  },
  {
    id: "alchemist",
    name: "炼金师",
    role: "燃烧回收",
    rarity: "epic",
    color: "#ff9f43",
    marbles: ["burn", "blast"],
    skillName: "热核反应",
    skillDesc: "引爆密集区域并点燃敌人，少量回收金币",
    skillCooldown: 24,
    passives: [
      { id: "alchemist_catalyst", name: "高温触媒", unlockLevel: 3, desc: "燃烧/爆裂弹珠伤害 +8%" },
      { id: "alchemist_salvage", name: "熔解回收", unlockLevel: 6, desc: "燃烧中的敌人死亡时额外获得 1 金币" },
      { id: "alchemist_core", name: "炼成爆心", unlockLevel: 10, desc: "爆炸半径 +10%，燃烧伤害 +10%" },
    ],
    routes: [
      {
        id: "alchemist_burn",
        name: "高温萃取",
        focus: "燃烧",
        desc: "燃烧弹珠伤害 +5%，燃烧伤害 +5% / 级",
        max: 8,
        baseCost: 84,
        growth: 1.45,
      },
      {
        id: "alchemist_gold",
        name: "战场回收",
        focus: "金币",
        desc: "发射频率 +2%，技能金币回收 +1 / 级",
        max: 8,
        baseCost: 92,
        growth: 1.48,
      },
      {
        id: "alchemist_reactor",
        name: "反应炉心",
        focus: "爆炸",
        desc: "爆炸伤害 +5%，技能冷却 -2.5% / 级",
        max: 6,
        baseCost: 116,
        growth: 1.52,
      },
    ],
  },
  {
    id: "frostseer",
    name: "霜语者",
    role: "冰霜控场",
    rarity: "epic",
    color: "#8de8ff",
    marbles: ["slow", "lightning"],
    skillName: "冰环静滞",
    skillDesc: "冻结敌人密集区域，并让减速目标受到额外伤害",
    skillCooldown: 25,
    passives: [
      { id: "frostseer_mark", name: "寒霜刻痕", unlockLevel: 3, desc: "减速弹珠伤害 +10%" },
      { id: "frostseer_spread", name: "冻结传导", unlockLevel: 6, desc: "减速持续 +0.35 秒，减速强度 +4%" },
      { id: "frostseer_weakness", name: "静滞破绽", unlockLevel: 10, desc: "减速目标受到霜语者伤害 +10%" },
    ],
    unlock: {
      type: "stage",
      stage: 11,
      desc: "通关第 1 章后解锁",
    },
    routes: [
      {
        id: "frostseer_slow",
        name: "寒霜刻印",
        focus: "减速",
        desc: "减速弹珠伤害 +5%，减速强度 +2% / 级",
        max: 8,
        baseCost: 90,
        growth: 1.46,
      },
      {
        id: "frostseer_chain",
        name: "冰晶导流",
        focus: "连锁",
        desc: "闪电伤害 +4%，每 3 级连锁 +1",
        max: 8,
        baseCost: 92,
        growth: 1.47,
      },
      {
        id: "frostseer_stasis",
        name: "静滞领域",
        focus: "技能",
        desc: "技能冷却 -2.5%，冻结持续 +0.18 秒 / 级",
        max: 6,
        baseCost: 118,
        growth: 1.53,
      },
    ],
  },
  {
    id: "voidbinder",
    name: "虚空使",
    role: "黑洞聚怪",
    rarity: "legendary",
    color: "#9f79ff",
    marbles: ["split", "blast"],
    skillName: "虚空坍缩",
    skillDesc: "牵引敌群到中心后爆破，适合处理高密度推进",
    skillCooldown: 26,
    passives: [
      { id: "voidbinder_rift", name: "裂隙扩容", unlockLevel: 3, desc: "分裂/爆裂弹珠伤害 +8%" },
      { id: "voidbinder_gravity", name: "引力残响", unlockLevel: 6, desc: "分裂弹珠存在时间 +0.35 秒，爆炸半径 +8%" },
      { id: "voidbinder_singularity", name: "奇点压缩", unlockLevel: 10, desc: "爆裂弹珠伤害 +12%" },
    ],
    unlock: {
      type: "collectible",
      collectible: "void_lens",
      amount: 1,
      desc: "获得 1 个棱镜残片后解锁",
    },
    routes: [
      {
        id: "voidbinder_split",
        name: "裂隙碎弹",
        focus: "分裂",
        desc: "分裂弹珠伤害 +4%，存在时间 +0.12 秒 / 级",
        max: 8,
        baseCost: 94,
        growth: 1.47,
      },
      {
        id: "voidbinder_blast",
        name: "坍缩爆心",
        focus: "爆炸",
        desc: "爆炸伤害 +5%，技能牵引范围 +3% / 级",
        max: 8,
        baseCost: 96,
        growth: 1.48,
      },
      {
        id: "voidbinder_core",
        name: "奇点核心",
        focus: "技能",
        desc: "技能冷却 -2.5%，技能伤害 +5% / 级",
        max: 6,
        baseCost: 122,
        growth: 1.54,
      },
    ],
  },
  {
    id: "treasurer",
    name: "财宝猎人",
    role: "战利品增幅",
    rarity: "legendary",
    color: "#ffd166",
    marbles: ["basic", "burn"],
    skillName: "点金弹雨",
    skillDesc: "发射金币弹幕，命中敌人时获得额外金币",
    skillCooldown: 21,
    passives: [
      { id: "treasurer_instinct", name: "寻宝直觉", unlockLevel: 3, desc: "战利品掉落幸运 +5%" },
      { id: "treasurer_silver", name: "银弹装填", unlockLevel: 6, desc: "基础/燃烧弹珠伤害 +8%" },
      { id: "treasurer_circuit", name: "金币回路", unlockLevel: 10, desc: "金币获得 +8%，主动技能金币收益 +6" },
    ],
    unlock: {
      type: "wins",
      wins: 3,
      desc: "完成 3 次章节通关后解锁",
    },
    routes: [
      {
        id: "treasurer_basic",
        name: "速射银弹",
        focus: "基础",
        desc: "基础弹珠伤害 +4%，发射频率 +1.5% / 级",
        max: 8,
        baseCost: 88,
        growth: 1.45,
      },
      {
        id: "treasurer_burn",
        name: "灼金火药",
        focus: "燃烧",
        desc: "燃烧弹珠伤害 +5%，燃烧伤害 +4% / 级",
        max: 8,
        baseCost: 92,
        growth: 1.47,
      },
      {
        id: "treasurer_luck",
        name: "好运契约",
        focus: "金币",
        desc: "发射频率 +2%，技能金币收益 +1 / 级",
        max: 6,
        baseCost: 116,
        growth: 1.52,
      },
    ],
  },
];
