import type { EnemyConfig, EnemyType } from "../core/types";

export const enemyConfigs: Record<EnemyType, EnemyConfig> = {
  small: {
    type: "small",
    name: "小方块",
    color: "#6ee7f9",
    hp: 20,
    speed: 58,
    radius: 18,
    exp: 2,
    coins: 1,
  },
  tank: {
    type: "tank",
    name: "厚甲块",
    color: "#9aa6b2",
    hp: 82,
    speed: 34,
    radius: 25,
    exp: 6,
    coins: 3,
    armor: 1,
  },
  fast: {
    type: "fast",
    name: "快速块",
    color: "#ff6c7e",
    hp: 18,
    speed: 105,
    radius: 15,
    exp: 3,
    coins: 1,
  },
  splitter: {
    type: "splitter",
    name: "分裂块",
    color: "#61e6a8",
    hp: 46,
    speed: 48,
    radius: 22,
    exp: 5,
    coins: 2,
  },
  shield: {
    type: "shield",
    name: "护盾块",
    color: "#b68cff",
    hp: 62,
    speed: 44,
    radius: 23,
    exp: 5,
    coins: 2,
    armor: 0.5,
  },
  healer: {
    type: "healer",
    name: "治疗块",
    color: "#f4a261",
    hp: 52,
    speed: 40,
    radius: 22,
    exp: 6,
    coins: 3,
  },
  gold: {
    type: "gold",
    name: "金币块",
    color: "#f6c95f",
    hp: 36,
    speed: 44,
    radius: 20,
    exp: 2,
    coins: 10,
  },
  elite: {
    type: "elite",
    name: "精英块",
    color: "#ff9f43",
    hp: 320,
    speed: 33,
    radius: 72,
    exp: 36,
    coins: 35,
    armor: 2,
  },
  boss: {
    type: "boss",
    name: "重装核心",
    color: "#ff5d73",
    hp: 1600,
    speed: 20,
    radius: 122,
    exp: 160,
    coins: 160,
    armor: 2.5,
  },
};
