import type { MarbleConfig, MarbleId } from "../core/types";

export const marbleConfigs: Record<MarbleId, MarbleConfig> = {
  basic: {
    id: "basic",
    name: "基础弹珠",
    color: "#eaf2ff",
    trail: "rgba(234, 242, 255, 0.34)",
    tags: ["physical"],
    damage: 12,
    cooldown: 1,
    speed: 545,
    lifetime: 4.4,
    radius: 8,
    maxBounce: 10,
  },
  split: {
    id: "split",
    name: "分裂弹珠",
    color: "#61e6a8",
    trail: "rgba(97, 230, 168, 0.34)",
    tags: ["physical", "multi"],
    damage: 8,
    cooldown: 1.45,
    speed: 500,
    lifetime: 4.5,
    radius: 9,
    maxBounce: 10,
  },
  blast: {
    id: "blast",
    name: "爆裂弹珠",
    color: "#f6c95f",
    trail: "rgba(246, 201, 95, 0.36)",
    tags: ["explosive"],
    damage: 10,
    cooldown: 1.65,
    speed: 475,
    lifetime: 4.1,
    radius: 10,
    maxBounce: 8,
  },
  burn: {
    id: "burn",
    name: "燃烧弹珠",
    color: "#ff7b5f",
    trail: "rgba(255, 123, 95, 0.32)",
    tags: ["elemental"],
    damage: 7,
    cooldown: 1.28,
    speed: 520,
    lifetime: 4.2,
    radius: 8,
    maxBounce: 9,
  },
  lightning: {
    id: "lightning",
    name: "闪电弹珠",
    color: "#b68cff",
    trail: "rgba(182, 140, 255, 0.32)",
    tags: ["elemental", "chain"],
    damage: 9,
    cooldown: 1.36,
    speed: 540,
    lifetime: 4.2,
    radius: 8,
    maxBounce: 9,
  },
  slow: {
    id: "slow",
    name: "减速弹珠",
    color: "#54c7ff",
    trail: "rgba(84, 199, 255, 0.34)",
    tags: ["control"],
    damage: 6,
    cooldown: 1.05,
    speed: 530,
    lifetime: 4.3,
    radius: 8,
    maxBounce: 10,
  },
};
