import type { ShopCategory, ShopItemConfig } from "../core/types";

export const shopCategories: Array<{ id: ShopCategory; label: string; hint: string }> = [
  { id: "recommended", label: "推荐", hint: "今日精选" },
  { id: "daily", label: "日常", hint: "每日补给" },
  { id: "growth", label: "成长", hint: "碎片宝石" },
  { id: "arena", label: "竞技", hint: "竞技币兑换" },
  { id: "crystal", label: "晶体", hint: "高级解锁" },
  { id: "bundles", label: "礼包", hint: "限购整备" },
];

export const dailyShopItems: ShopItemConfig[] = [
  {
    id: "daily_free_supply",
    category: "daily",
    name: "今日免费补给",
    desc: "每日免费资源",
    price: { currency: "energyCrystals", amount: 0 },
    stock: 1,
    refresh: "daily",
    rewards: [
      { type: "coins", amount: 80 },
      { type: "randomMarbleShard", amount: 3 },
    ],
  },
  {
    id: "daily_training_cache",
    category: "daily",
    name: "训练碎片箱",
    desc: "金币购买的随机碎片",
    price: { currency: "coins", amount: 160 },
    stock: 1,
    refresh: "daily",
    rewards: [{ type: "randomMarbleShard", amount: 6 }],
  },
  {
    id: "daily_tactical_cache",
    category: "daily",
    name: "战术碎片箱",
    desc: "金币购买的较多碎片",
    price: { currency: "coins", amount: 320 },
    stock: 1,
    refresh: "daily",
    rewards: [{ type: "randomMarbleShard", amount: 14 }],
  },
];

export const shardShopItems: ShopItemConfig[] = [
  {
    id: "shard_basic",
    category: "growth",
    name: "基础弹珠碎片",
    desc: "稳定补齐基础弹珠",
    price: { currency: "coins", amount: 220 },
    stock: 2,
    refresh: "daily",
    rewards: [{ type: "marbleShard", marbleId: "basic", amount: 10 }],
  },
  {
    id: "shard_split",
    category: "growth",
    name: "分裂弹珠碎片",
    desc: "补充多弹反弹构筑",
    price: { currency: "coins", amount: 260 },
    stock: 2,
    refresh: "daily",
    rewards: [{ type: "marbleShard", marbleId: "split", amount: 8 }],
  },
  {
    id: "shard_blast",
    category: "growth",
    name: "爆裂弹珠碎片",
    desc: "补充范围爆破构筑",
    price: { currency: "coins", amount: 280 },
    stock: 2,
    refresh: "daily",
    rewards: [{ type: "marbleShard", marbleId: "blast", amount: 8 }],
  },
  {
    id: "shard_burn",
    category: "growth",
    name: "燃烧弹珠碎片",
    desc: "补充持续燃烧构筑",
    price: { currency: "coins", amount: 260 },
    stock: 2,
    refresh: "daily",
    rewards: [{ type: "marbleShard", marbleId: "burn", amount: 8 }],
  },
  {
    id: "shard_lightning",
    category: "growth",
    name: "闪电弹珠碎片",
    desc: "补充连锁清场构筑",
    price: { currency: "coins", amount: 300 },
    stock: 2,
    refresh: "daily",
    rewards: [{ type: "marbleShard", marbleId: "lightning", amount: 8 }],
  },
  {
    id: "shard_slow",
    category: "growth",
    name: "减速弹珠碎片",
    desc: "补充控制压制构筑",
    price: { currency: "coins", amount: 260 },
    stock: 2,
    refresh: "daily",
    rewards: [{ type: "marbleShard", marbleId: "slow", amount: 8 }],
  },
];

export const gemShopItems: ShopItemConfig[] = [
  {
    id: "gem_power_1",
    category: "growth",
    name: "强袭宝石原胚",
    desc: "全队伤害宝石",
    price: { currency: "coins", amount: 620 },
    stock: 1,
    refresh: "daily",
    rewards: [{ type: "gem", gemType: "power", level: 1, amount: 1 }],
  },
  {
    id: "gem_guard_1",
    category: "growth",
    name: "壁垒宝石原胚",
    desc: "基地生命宝石",
    price: { currency: "coins", amount: 620 },
    stock: 1,
    refresh: "daily",
    rewards: [{ type: "gem", gemType: "guard", level: 1, amount: 1 }],
  },
  {
    id: "gem_fortune_1",
    category: "growth",
    name: "回收宝石原胚",
    desc: "金币与掉落宝石",
    price: { currency: "coins", amount: 700 },
    stock: 1,
    refresh: "daily",
    rewards: [{ type: "gem", gemType: "fortune", level: 1, amount: 1 }],
  },
  {
    id: "gem_swift_1",
    category: "growth",
    name: "迅捷宝石原胚",
    desc: "全队发射频率宝石",
    price: { currency: "coins", amount: 660 },
    stock: 1,
    refresh: "daily",
    rewards: [{ type: "gem", gemType: "swift", level: 1, amount: 1 }],
  },
  {
    id: "gem_focus_1",
    category: "growth",
    name: "专注宝石原胚",
    desc: "主动技能冷却宝石",
    price: { currency: "coins", amount: 680 },
    stock: 1,
    refresh: "daily",
    rewards: [{ type: "gem", gemType: "focus", level: 1, amount: 1 }],
  },
  {
    id: "gem_rupture_1",
    category: "growth",
    name: "锐击宝石原胚",
    desc: "暴击率与暴伤宝石",
    price: { currency: "coins", amount: 720 },
    stock: 1,
    refresh: "daily",
    rewards: [{ type: "gem", gemType: "rupture", level: 1, amount: 1 }],
  },
];

export const arenaShopItems: ShopItemConfig[] = [
  {
    id: "arena_daily_cache",
    category: "arena",
    name: "竞技补给箱",
    desc: "每日竞技基础补给",
    price: { currency: "pvpCoins", amount: 180 },
    stock: 1,
    refresh: "daily",
    rewards: [
      { type: "randomMarbleShard", amount: 18 },
      { type: "ticket", ticketId: "refresh", amount: 1 },
    ],
  },
  {
    id: "arena_precision_shards",
    category: "arena",
    name: "精准弹珠箱",
    desc: "竞技常用弹珠材料",
    price: { currency: "pvpCoins", amount: 260 },
    stock: 2,
    refresh: "daily",
    unlock: { type: "pvpRank", mode: "duel", tier: "silver", division: 3, desc: "达到白银 III 解锁" },
    rewards: [
      { type: "marbleShard", marbleId: "lightning", amount: 10 },
      { type: "marbleShard", marbleId: "slow", amount: 10 },
    ],
  },
  {
    id: "arena_guard_core",
    category: "arena",
    name: "防线宝石箱",
    desc: "适合自动对战的稳定宝石",
    price: { currency: "pvpCoins", amount: 420 },
    stock: 1,
    refresh: "weekly",
    unlock: { type: "pvpRank", mode: "duel", tier: "silver", division: 1, desc: "达到白银 I 解锁" },
    rewards: [
      { type: "gem", gemType: "guard", level: 1, amount: 1 },
      { type: "gem", gemType: "focus", level: 1, amount: 1 },
    ],
  },
  {
    id: "arena_insurance_bundle",
    category: "arena",
    name: "竞技保险券组",
    desc: "用于搜打撤保护高价值掉落",
    price: { currency: "pvpCoins", amount: 320 },
    stock: 2,
    refresh: "weekly",
    unlock: { type: "pvpRank", mode: "duel", tier: "silver", division: 2, desc: "达到白银 II 解锁" },
    rewards: [{ type: "ticket", ticketId: "insurance", amount: 2 }],
  },
  {
    id: "arena_elite_cache",
    category: "arena",
    name: "精英竞技箱",
    desc: "高段位周限购成长材料",
    price: { currency: "pvpCoins", amount: 760 },
    stock: 1,
    refresh: "weekly",
    unlock: { type: "pvpRank", mode: "duel", tier: "gold", division: 3, desc: "达到黄金 III 解锁" },
    rewards: [
      { type: "randomMarbleShard", amount: 36 },
      { type: "gem", gemType: "rupture", level: 1, amount: 1 },
      { type: "ticket", ticketId: "scan", amount: 2 },
    ],
  },
];

export const crystalShopItems: ShopItemConfig[] = [
  {
    id: "unlock_frostseer",
    category: "crystal",
    name: "霜语者授权",
    desc: "提前解锁冰霜控场角色",
    price: { currency: "energyCrystals", amount: 180 },
    stock: 1,
    refresh: "once",
    rewards: [{ type: "characterUnlock", characterId: "frostseer" }],
  },
  {
    id: "unlock_voidbinder",
    category: "crystal",
    name: "虚空使授权",
    desc: "提前解锁黑洞聚怪角色",
    price: { currency: "energyCrystals", amount: 360 },
    stock: 1,
    refresh: "once",
    rewards: [{ type: "characterUnlock", characterId: "voidbinder" }],
  },
  {
    id: "unlock_treasurer",
    category: "crystal",
    name: "财宝猎人授权",
    desc: "提前解锁战利品增幅角色",
    price: { currency: "energyCrystals", amount: 360 },
    stock: 1,
    refresh: "once",
    rewards: [{ type: "characterUnlock", characterId: "treasurer" }],
  },
  {
    id: "ticket_insurance_weekly",
    category: "crystal",
    name: "撤离保险券",
    desc: "搜打撤高级道具",
    price: { currency: "energyCrystals", amount: 60 },
    stock: 3,
    refresh: "weekly",
    rewards: [{ type: "ticket", ticketId: "insurance", amount: 2 }],
  },
  {
    id: "ticket_scan_weekly",
    category: "crystal",
    name: "战术扫描券",
    desc: "升级选择辅助道具",
    price: { currency: "energyCrystals", amount: 40 },
    stock: 3,
    refresh: "weekly",
    rewards: [{ type: "ticket", ticketId: "scan", amount: 2 }],
  },
];

export const bundleShopItems: ShopItemConfig[] = [
  {
    id: "starter_energy_bundle",
    category: "bundles",
    name: "新手整备包",
    desc: "账号一次的成长礼包",
    price: { currency: "energyCrystals", amount: 68 },
    stock: 1,
    refresh: "once",
    rewards: [
      { type: "coins", amount: 300 },
      { type: "marbleShard", marbleId: "basic", amount: 20 },
      { type: "gem", gemType: "power", level: 1, amount: 1 },
    ],
  },
  {
    id: "rebound_weekly_bundle",
    category: "bundles",
    name: "反弹构筑包",
    desc: "基础与分裂构筑材料",
    price: { currency: "energyCrystals", amount: 88 },
    stock: 1,
    refresh: "weekly",
    rewards: [
      { type: "marbleShard", marbleId: "basic", amount: 18 },
      { type: "marbleShard", marbleId: "split", amount: 18 },
      { type: "ticket", ticketId: "refresh", amount: 1 },
    ],
  },
  {
    id: "deep_extraction_weekly_bundle",
    category: "bundles",
    name: "深层撤离包",
    desc: "保险券与随机成长材料",
    price: { currency: "energyCrystals", amount: 128 },
    stock: 1,
    refresh: "weekly",
    rewards: [
      { type: "ticket", ticketId: "insurance", amount: 3 },
      { type: "randomMarbleShard", amount: 30 },
      { type: "gem", gemType: "fortune", level: 1, amount: 1 },
    ],
  },
];

export const shopItems = [...dailyShopItems, ...shardShopItems, ...gemShopItems, ...arenaShopItems, ...crystalShopItems, ...bundleShopItems];
