import type { TacticalDeckConfig } from "../core/types";

export const tacticalDecks: TacticalDeckConfig[] = [
  {
    id: "auto",
    name: "自动推荐",
    desc: "根据阵法、角色、弹珠和羁绊自动选择本局卡组。",
    tagHints: ["自动", "推荐"],
    cardIds: [],
  },
  {
    id: "custom",
    name: "自定义卡组",
    desc: "使用玩家在作战终端中配置的卡组。",
    tagHints: ["自定义", "构筑"],
    cardIds: [],
  },
  {
    id: "rebound",
    name: "回环裂变",
    desc: "围绕反弹、多弹和分裂弹幕成型。",
    formationHint: "rebound",
    tagHints: ["反弹", "多弹", "弹珠"],
    cardIds: [
      "damage_up",
      "damage_up_mid",
      "fire_rate",
      "fire_rate_mid",
      "marble_speed",
      "global_pierce",
      "bounce_damage",
      "split_more",
      "multi_swarm",
      "core_rebound_fracture",
      "core_swarm_growth",
      "engineer_haste",
      "prism_refraction_card",
      "bond_refraction_workshop",
      "utility_refresh_charge",
      "utility_assault_bias",
      "base_hp",
      "last_line",
    ],
  },
  {
    id: "pyro",
    name: "灼爆引擎",
    desc: "围绕燃烧、爆炸和击杀扩散成型。",
    formationHint: "pyro",
    tagHints: ["燃烧", "爆炸", "经济"],
    cardIds: [
      "damage_up",
      "damage_up_mid",
      "fire_rate",
      "crit",
      "crit_mid",
      "blast_radius",
      "chain_blast",
      "burn_plus",
      "burn_spread",
      "core_pyro_chain",
      "bomber_energy",
      "alchemist_recycle_card",
      "bond_molten_charge",
      "bond_golden_fuel",
      "gold_damage",
      "coin_gain",
      "utility_refresh_charge",
      "base_hp",
    ],
  },
  {
    id: "magnetic",
    name: "静电磁控",
    desc: "围绕闪电、减速和控制增伤成型。",
    formationHint: "magnetic",
    tagHints: ["连锁", "控制", "暴击"],
    cardIds: [
      "damage_up",
      "fire_rate",
      "crit",
      "crit_mid",
      "crit_damage",
      "lightning_chain",
      "lightning_focus",
      "slow_power",
      "slow_vulnerability",
      "core_static_frost",
      "core_boss_hunter",
      "magnet_long",
      "sentinel_barrier_card",
      "bond_static_frost_ring",
      "bond_bulwark_suppression",
      "utility_refresh_charge",
      "utility_rarity_boost",
      "base_hp",
    ],
  },
  {
    id: "hunter",
    name: "猎核歼灭",
    desc: "围绕暴击、精英/BOSS 压制和技能回充成型。",
    formationHint: "hunter",
    tagHints: ["暴击", "Boss", "角色"],
    cardIds: [
      "damage_up",
      "damage_up_mid",
      "fire_rate",
      "crit",
      "crit_mid",
      "crit_high",
      "crit_damage",
      "boss_killer",
      "core_boss_hunter",
      "core_boss_hunter_plus",
      "global_pierce",
      "prism_refraction_card",
      "bond_hunt_mark",
      "utility_rarity_boost",
      "utility_assault_bias",
      "base_hp",
    ],
  },
  {
    id: "guard",
    name: "底线壁垒",
    desc: "围绕基地生命、减速控制和底线反击成型。",
    formationHint: "guard",
    tagHints: ["生存", "控制", "全队"],
    cardIds: [
      "base_hp",
      "regen_wave",
      "revive",
      "last_line",
      "slow_power",
      "slow_vulnerability",
      "core_last_line",
      "core_last_line_plus",
      "sentinel_barrier_card",
      "bond_bulwark_suppression",
      "bond_high_frequency_matrix",
      "damage_up",
      "fire_rate",
      "utility_refresh_charge",
      "utility_rarity_boost",
    ],
  },
  {
    id: "bounty",
    name: "赏金燃料",
    desc: "围绕金币、成长和资源转化火力成型。",
    formationHint: "bounty",
    tagHints: ["经济", "成长", "燃烧"],
    cardIds: [
      "coin_gain",
      "xp_gain",
      "gold_damage",
      "burn_plus",
      "burn_spread",
      "blast_radius",
      "core_pyro_chain",
      "core_pyro_chain_plus",
      "alchemist_recycle_card",
      "bond_golden_fuel",
      "bond_molten_charge",
      "utility_attribute_echo",
      "utility_rarity_boost",
      "damage_up",
      "base_hp",
    ],
  },
];

export function tacticalDeckById(id: string | undefined) {
  return tacticalDecks.find((deck) => deck.id === id) || tacticalDecks[0];
}
